name: Deploy to InfinityFree

on:
  push:
    branches:
      - main   # jalan kalau push ke branch 'main'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftpupload.net
          username: if0_39689837      # ganti dengan username FTP InfinityFree
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
